name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**' 

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
      ports:
        - 3306:3306
      options: >-
        --health-cmd="mysqladmin ping -uroot -prootpassword"
        --health-interval=10s
        --health-timeout=5s
        --health-retries=3